### ISSUE TITLE
Wrong detection for almost exactly similar but different licenses

### ISSUE THREAD

**Issue by prathamgahlout** [prathamgahlout/phsyberdome-dependency-scanner#16]
The license detector is detecting Apache-2.0 as a Pixar license.
The reason being that the Pixar license is a modified version of the Apache-2.0 so while calculating the similarity, Pixar scores greater than Apache-2.0 by a very little margin.

What I will do is if the similarity score of lets say N number of licenses are very close ( within a range [ most_similar, most_similar - a ] , where a will be a number defined after some tests ), the detector will give all N licenses as possible right answers.

**Comment by abhiramkarri** [comment]
@prathamgahlout I'm interested in this bug and have a few questions.
1. Can you define an acceptance criteria so I know exactly how to resolve issue.
2. How is the factor "a" defined?
3. How can I reproduce the issue? Is there a playground link?
4. Where do I start on this issue? Which file do I update for changes in comparing licenses?

**Comment by prathamgahlout** [comment]
Hello @abhiramkarri ,

I should have added all these, anyways Thanks!

**Reproduction:**
1. Scan this repository with
`java -jar phsyberdome-sca-cli-1.0.2.beta-jar-with-dependencies.jar monitor -src https://github.com/prathamgahlout/phsyberdome-dependency-scanner.git`
2. After the scan is complete you would see the maven dependency tree and with their license adjacent to their names. One can notice that the packages with licenses as Apache-2.0 are being detected as Pixar. You can cross check these from the central maven repository [Maven Central](https://mvnrepository.com/repos/central).

**Explanation:**
In the License Detector Module we are calculating the similarity index of the package's license content from the licenses available in the SPDX repository. The higher the similarity index, more probability that it is the same license.

Now consider a case wherein we are calculating the similarity index of license B & C with license A. License B & C both could be almost similar to A, which will result in indexes with only a slight difference. For example, [A ~ B] = 0.89 & [A ~ C] = 0.90, where ~ represents calculation of text content similarity.
By the current logic, our detector would give C as its the highest and hence has more probability of being the correct license, but as we can notice such small differences could result in wrong detection as we have seen in the case of Apache-2.0 & Pixar.

We can define a number `a` that would give us a range [ most_similar - a ] ( [0.90 - a]  in the above case ), where we say that licenses having similarity index in this range are all probable answers.

**Acceptance Criteria:**
1. The dependency tree should be printed as such that all probable Licenses are printed adjacent to the dependency concatenated with `|` character. For example,
`dep-name@version[Apache-2.0 | Pixar | AnyOtherLicenseMaybe ]`

Now the answer for your last question, please look into the files,
[LicenseDetector](https://github.com/prathamgahlout/phsyberdome-dependency-scanner/blob/master/src/main/java/com/phsyberdome/drona/licensedetector/LicenseDetector.java)

[Module](https://github.com/prathamgahlout/phsyberdome-dependency-scanner/blob/master/src/main/java/com/phsyberdome/drona/Models/Module.java)We would have to change this to accommodate a list of probable licenses instead of just 1.

[DependencyTree](https://github.com/prathamgahlout/phsyberdome-dependency-scanner/blob/master/src/main/java/com/phsyberdome/drona/Models/DependencyTree.java)

Get the latest release from the release section.

Thanks for looking into this! Feel free to ask for more clarification.

**Comment by abhiramkarri** [comment]
Thanks for the information, I'll get started on this. Can you assign it to me?

**Comment by prathamgahlout** [comment]
Hi @abhiramkarri , as this was a major issue, it has been fixed as been fixed as part of this #37
